services: 
###################  RabbitMQ SERVICE ########################
  rabbit: 
    image: rabbitmq:4-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service
      
###################  Accounts DB SERVICE ########################
  accountsdb: 
    container_name: accountsdb-cnt
    ports:
      - 8084:5432
    environment:
      POSTGRES_DB: accountsdb #DB name 
    extends:
      file: common-config.yml
      service: microservice-db-config
      
###################  Cards DB SERVICE ########################
  cardsdb:
    container_name: cardsdb-cnt
    ports:
      - 8085:5432
    environment:
      POSTGRES_DB: cardsdb #DB name
    extends:
      file: common-config.yml
      service: microservice-db-config
      
###################  Loans DB SERVER ########################      
  loansdb:
    container_name: loansdb-cnt
    ports:
      - 8086:5432
    environment:
      POSTGRES_DB: loansdb #DB name
    extends:
      file: common-config.yml
      service: microservice-db-config

###################  Config SERVICE ########################
  configserver: 
    image: "devsoncall/configserver:v3.0_addEureka" # TODO - PUSH iamges & replace with vivekd123 in end
    container_name: configserver-cnt
    ports:
      - "8090:8090"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
      
###################  Eureka SERVICE ########################
  eurekaserver:
      image: "devsoncall/eurekaserver:v3.0_addEureka" # TODO - PUSH iamges & replace with vivekd123 in end
      container_name: "eurekaserver-cnt"
      ports: 
        - "8092:8092"
      depends_on:
        configserver:
          condition: service_healthy
      healthcheck:
        test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 10s
      extends:
        file: common-config.yml
        service: microservice-configserver-config
      
###################  ACCOUNTS SERVICE ########################
  accounts: 
    image: "devsoncall/accounts:v3.0_addEureka" # TODO - PUSH iamges & replace with vivekd123 in end
    container_name: accounts-cnt
    ports:
      - "8081:8081"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://accountsdb:5432/accountsdb" #JDBC protocol-host-port-db)
    extends:
      file: common-config.yml
      service: microservice-eureka-config

###################  CARDS SERVICE ########################
  cards: 
    image: "devsoncall/cards:v3.0_addEureka" # TODO - PUSH iamges & replace with vivekd123 in end
    container_name: cards-cnt
    ports:
      - "8082:8082"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://cardsdb:5432/cardsdb" #JDBC protocol-host-port-db)
    extends:
      file: common-config.yml
      service: microservice-eureka-config

###################  LOANS SERVER ########################      
  loans: 
    image: "devsoncall/loans:v3.0_addEureka" # TODO - PUSH iamges & replace with vivekd123 in end
    container_name: loans-cnt
    ports:
      - "8083:8083"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://loansdb:5432/loansdb" #JDBC protocol-host-port-db)
    extends:
      file: common-config.yml
      service: microservice-eureka-config
      
###################  Others ########################
networks:
  devsoncallNetwork: #NETWORK name inside docker
    driver: "bridge"