services:
############### Common Network SERVICE ##################
  network-deploy-service:
    networks:
      - devsoncallNetwork
      
############### Microservices base Configs ##############
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

############### Base + Config-Server configs  #############
  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: prod # ACTIVE-PROFILE
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8090/

#################### DB Configs #######################
  microservice-db-config:
    extends:
      service: network-deploy-service
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
