server:
  port: 8082

spring:
  application:
    name: "cards"
  datasource:
    url: jdbc:postgresql://localhost:8085/cardsdb
    driver-class-name: org.postgresql.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8090/"

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
