server:
  port: 8082

spring:
  application:
    name: "cards"
  datasource:
    url: jdbc:postgresql://localhost:8085/cardsdb #fallback -gets Overidden when used docker-compose by cards:8085
    driver-class-name: org.postgresql.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8090/" #fallback -gets Overidden when used docker-compose by configserver:8090

  rabbitmq:
    host: localhost  #fallback in docker-compose
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
      
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8092/eureka/ #fallback
      
info: #Actuator
  app:
    name: "accounts"
    description: "Accounts Microservice"
    version: "1.0.0"
